init translation of symbols
ts-zh-docs/TypeScript-zh-Website pull request #91
Opened 2024-10-07 12:56 UTC by hanyujie2002

2024-10-12 00:23 UTC, awxiaoxian2020 requested changes

2024-10-12 00:23 UTC, awxiaoxian2020 commented on docs/documentation/zh/reference/Symbols.md
> +title: 符号
```suggestion
title: Symbol
```

2024-10-12 00:23 UTC, awxiaoxian2020 commented on docs/documentation/zh/reference/Symbols.md
> +title: 符号
建议保留英文原文

2024-10-24 13:29 UTC, hanyujie2002 commented on docs/documentation/zh/reference/Symbols.md
> +符号是不可变且唯一的。
```suggestion
Symbol 不可变且唯一。
```

2024-10-24 13:29 UTC, hanyujie2002 commented on docs/documentation/zh/reference/Symbols.md
> +sym2 === sym3; // false，符号是唯一的
```suggestion
sym2 === sym3; // false，symbol 唯一
```

2024-10-26 04:47 UTC, awxiaoxian2020 approved these changes

2024-10-26 04:47 UTC, merged